# Generated by Django 4.1.7 on 2023-03-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='url',
        ),
    ]
