# Generated by Django 4.1.7 on 2023-03-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_menuitems_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
