# Generated by Django 4.1.7 on 2023-03-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_menuitems_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='named_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
